Samples:
    10X_P4_0:
    10X_P4_1:
    10X_P4_2:
    10X_P4_3:
    10X_P4_4:
    10X_P4_5:
    10X_P4_6:
    10X_P4_7:
    10X_P7_0:
    10X_P7_1:
    10X_P7_10:
    10X_P7_11:
    10X_P7_12:
    10X_P7_13:
    10X_P7_14:
    10X_P7_15:
    10X_P7_2:
    10X_P7_3:
    10X_P7_4:
    10X_P7_5:
    10X_P7_6:
    10X_P7_7:
    10X_P7_8:
    10X_P7_9:
    10X_P8_12:
    10X_P8_13:
    10X_P8_14:
    10X_P8_15:

GENOMEREF: /fs/cbsuvlaminck2/workdir/fw262/references/GRCm38/GRCm38.primary_assembly.genome.fa
REFGTF: /fs/cbsuvlaminck2/workdir/fw262/references/GRCm38/gencode.vM21.annotation.gtf

SAMPWDIR:   sampwdir/
DATADIR: data
    
TMPDIR: temp

PIPELINE_MAJOR: ../results_MouseAtlas_fromFastq

SPECIES:
    - mouseAtlas
GLOBAL:
    allowed_mismatch: 10
    BC_range:
        first: 1
        last: 16
    UMI_range:
        first: 17
        last: 26 # 28 for v3, up to 26 for v2

BOWTIE: /programs/bowtie2-2.3.0/bowtie2
PICARD: /programs/picard-tools-2.1.1/picard.jar
DROPSEQ: /home/av486/Desktop/Tools/Drop-seq_tools-1.12/
GTFTOGENEPRED: /fs/cbsuvlaminck2/workdir/fw262/tools/gtfToGenePred
STAREXEC: /programs/STAR-2.5/bin/Linux_x86_64/STAR
FASTQCEXEC: fastqc
CORES: 10 
expectedCells: 5000
MINCOV: 5
MERGEBP: 500

#REFFLAT: /workdir/References/Chick/GRCg6a/refFlat_ensembl.refFlat.filled.refFlat
#REFFLAT_HMM_withDir: /workdir/fw262/ShaoPei/chickenAll/all_Aligned_sorted_2_merge500_5reads.bed.withDir.refFlat_ensembl.refFlat.filled.refFlat
#REFFLAT_HMM_noDir: /workdir/fw262/ShaoPei/chickenAll/all_Aligned_sorted_2_merge500_5reads.bed.noDir.refFlat_ensembl.refFlat.filled.refFlat
#METAREF: /workdir/References/Chick/GRCg6a/STAR_noAnno

splitBams:
    combined_bam.REF_chrM.bam:
    #combined_bam.REF_chrX.bam:
    #combined_bam.REF_chr19.bam:
    #combined_bam.REF_chr18.bam:
    #combined_bam.REF_chr17.bam:
    #combined_bam.REF_chr15.bam:
    #combined_bam.REF_chr16.bam:
    #combined_bam.REF_chr14.bam:
    #combined_bam.REF_chr12.bam:
    #combined_bam.REF_chr13.bam:
    #combined_bam.REF_chr10.bam:
    combined_bam.REF_chr11.bam:
    #combined_bam.REF_chr9.bam:
    #combined_bam.REF_chr8.bam:
    #combined_bam.REF_chr7.bam:
    #combined_bam.REF_chr6.bam:
    #combined_bam.REF_chr5.bam:
    #combined_bam.REF_chr4.bam:
    #combined_bam.REF_chr3.bam:
    #combined_bam.REF_chr2.bam:
    #combined_bam.REF_chr1.bam:
    #combined_bam.REF_chrY.bam:

